### ISSUE TITLE
Call audio & cpu stats

### ISSUE THREAD

**Issue by weritos666** [nichcream/rel#1]
I installed your los build with kernel 4.9
Bugs:
- There is no sound when making a call (I do not hear and I do not hear)
Logcat Full - https://del.dog/lajuxuseco
Logcat Filter E - https://del.dog/ujodequboq.sql

- Unable to get processor frequency statistics
Logcat Filter E - https://del.dog/exozagasad.sql

**Comment by prin2ce** [comment]
@nichcream will this ROM work commonly both on land and santoni ? :-)

**Comment by nichcream** [comment]
Acked. I'll try to get these solved in the next build.

**Comment by abhishekpandey7148** [comment]
Waiting for new build 😍😍😍

**Comment by AltafYafai** [comment]
Me too waiting for new Build...🤩🤩

**Comment by rupansh** [comment]
Iommu v1 driver plox. The one you are using which has a seperate platform bus and doesnt splash loop ;-;

**Comment by nichcream** [comment]
[20190414.0-beta4.9-land](https://github.com/nichcream/rel/releases/tag/20190414.0-beta4.9-land)
Please check if the bugs are present in this build.

**Comment by weritos666** [comment]
> Acked. I'll try to get these solved in the next build.

Installed a new build of April 14:
- frequency statistics work

- The audio call does not work

**Comment by abhishekpandey7148** [comment]
@weritos666 :sob::sob::sob::cry:

**Comment by AltafYafai** [comment]
Waiting for new build with incoming and outgoing call audio fix.. :cry:

**Comment by AltafYafai** [comment]
@nichcream tested the latest 15-04-2019 Los build.

All basic things working fine.

Call audio fixed.
WiFi working
BT working
Volte working flawlessly
Hotspot working fine
Night mode working fine
Cam working fine

In Short all basic things working fine in latest build.

Thank you so much.
