### ISSUE TITLE
Does not charge up to 100%

### ISSUE THREAD

**Issue by weritos666** [nichcream/rel#2]
My smartphone was charging all night (about 6 hours).
In the morning, it was only 99%

**Comment by AltafYafai** [comment]
Nop... Here it is fine bro... It gets charged 100%

**Comment by nichcream** [comment]
Facing a similar issue. Except that mine charges to 100%, but drains down to 99% very quickly. This is definitely an issue to look into, though not exactly urgent since it doesn't impact overall battery performance.

**Comment by lukmanshaikh** [comment]
@nichcream Yeah that's not a major issue.Anyways thanks for your contributions for land.Waiting for device sources 👍

**Comment by abhishekpandey7148** [comment]
All working fine for me !
[Check this screenshot](https://telegra.ph/file/15b6eb13b97ff5412b720.jpg)

**Comment by abhishekpandey7148** [comment]
https://telegra.ph/file/15b6eb13b97ff5412b720.jpg
