### ISSUE TITLE
After charging, the smartphone does not go into deep sleep

### ISSUE THREAD

**Issue by weritos666** [nichcream/rel#3]
After charging, the smartphone does not go into deep sleep
per night consumes 20%
https://c.radikal.ru/c04/1904/e9/eee37e4edd54.png

**Comment by ghost** [comment]
Was the same. Rebooting after disconnecting the charger helped. Now I dont see this problem.

**Comment by AltafYafai** [comment]
Same issue i have Faced. Have To Restart For Deep Sleep after Charge.

**Comment by ghost** [comment]
I suspect, this affects not only deep sleep, but also drains battery. Very bad ratio of screen time/percent of battery, when I see this wakelock

**Comment by nichcream** [comment]
What wakelock exactly?

**Comment by ghost** [comment]
78db000.usb

**Comment by nungkham** [comment]
I also have the same problem after flashing a custom aosp rom on my redmi device. The problem is that the Google Android auto app calls usb permissions after unplugging the cable, so the solution is to force stop it, or uninstall it if you don't regularly use it to connect to your car.

**Comment by nungkham** [comment]
Faced same issue. Have to reboot the phone after unplugged charger. Tried kill ground services, disable 78db000.usb wakelock but connecting to charger, things happening. Tried change cable /wall supplier but still nothing changed.
