### ISSUE TITLE
Display Flickering Issue. on Latest 19-4-19 LOS 4.9 Build.

### ISSUE THREAD

**Issue by AltafYafai** [nichcream/rel#6]
Flashed Latest LOS 4.9 19-4-19 Build.

After Booting Rom ( 1St Boot ) The Display Flickering Heavily.

I Thought My Display Gone.

Then I Have Restarted Phone And It Got Fixed.

But Many Users Faced Same Issue.

Please Kindly Look into This Issue And Fix it Accordingly.

I Am Not Able To Give Logs Because Now its Fixed And On Screen Recording its Not Visible.

**Comment by deccan451** [comment]
Yeah I too faced it suddenly I thought it's time to buy new phone ;)

**Comment by Sushantdk123** [comment]
No logs. No Report. 😂😂🤣🤣. Get logs then Report.

**Comment by nichcream** [comment]
> No logs. No Report. . Get logs then Report.

You heard the man. I can't validate this bug since I've never faced anything like that. Please get a kernel log if anyone hits this issue.

**Comment by ghost** [comment]
I see this when I open chat of broadcasts in the YouTube application. Can't get log now, maybe later.
04.15 build

**Comment by nichcream** [comment]
This is extremely confusing. Some told me it was screen tearing and not flickering. Please do confirm because flickering ≠ tearing.

**Comment by ghost** [comment]
No tearing. Flickering

**Comment by weritos666** [comment]
> This is extremely confusing. Some told me it was screen tearing and not flickering. Please do confirm because flickering ≠ tearing.

So 
1 - Video demonstration (https://drive.google.com/file/d/1oOb08UHFtFN0qXwG964j2fccwjDUc5bM/view)

2 - Logcat E - > https://del.dog/ayapidarig

3 - Logcat - > https://del.dog/agehaqadux.pl

4 - Logcat dmesg - > https://drive.google.com/file/d/1xltDx7EWkn_bJBdiP10CELiMm8FcKS6L/view?usp=sharing

**Comment by obscenelyvague** [comment]
You've got to be kidding me.

**Comment by nikhil-hari** [comment]
Redmi 3S Prime (3GB/32GB), FPC. All partitions on ext4, not encrypted.
Clean flashed thrice. Didn't face any flicker. 
That's ROM alone once, then ROM+GApps+Magisk (v19, beta channel)
Also, didn't face any issues per se, except for one random reboot which could've been my mishap (tried playing around in FK Manager).

**Comment by arizaini** [comment]
> Redmi 3S Prime (3GB/32GB), FPC. All partitions on ext4, not encrypted.
> Clean flashed thrice. Didn't face any flicker.
> That's ROM alone once, then ROM+GApps+Magisk (v19, beta channel)
> Also, didn't face any issues per se, except for one random reboot which could've been my mishap (tried playing around in FK Manager).

encryption fine here (land, goodix, ext4, 3/32) clean flash every new build available..., if you already format data long ago before flash this build (k4.9) off course it will not encrypted, one issue for me is mobile data need to be triggered by making call to show that (LTE... etc) icon on status bar...otherwise it will not show up...idk it's my modem phone problem or what...

**Comment by nikhil-hari** [comment]
Just tried what @arizaini reported. I can confirm, I have the issue too. However, Internet connectivity still works, just that the LTE symbol disappears. Can be ignored.

**Comment by arizaini** [comment]
> Just tried what @arizaini reported. I can confirm, I have the issue too. However, Internet connectivity still works, just that the LTE symbol disappears. Can be ignored.

ya it can be ignore... but whenever i start the phone or reboot it, need to be triggered... then all notification will working
