### ISSUE TITLE
FM radio no audio

### ISSUE THREAD

**Issue by prin2ce** [nichcream/rel#8]
Audio from FM radio is not working in santoni 4.9 ROM , though it is able to recognize all the radio channels but no audio output is coming from FM radio

https://drive.google.com/file/d/1T4RsiEIP-gqwRdOzahOnAIxi7swj5YWs/view?usp=drivesdk

Logcat from matlog app

**Comment by prin2ce** [comment]
@t0ssox can you please confirm whether  FM radio works for you +_+

**Comment by vvr3ddy** [comment]
> @t0ssox can you please confirm whether FM radio works for you +_+

It works absolutely fine for me, i can even record

**Comment by prin2ce** [comment]
@Quantummech2000 thanks for reply bro :), idk why it doesn't work for me , no sound at all :( can you please have a look at the logs if you have free time

**Comment by vvr3ddy** [comment]
> @Quantummech2000 thanks for reply bro :), idk why it doesn't work for me , no sound at all :( can you please have a look at the logs if you have free time

Can u grab ADB logs, they'd be better useful

**Comment by prin2ce** [comment]
@Quantummech2000 No PC bro , nvm I'll wait for another build maybe it gets fixed in that build :kissing_closed_eyes:

**Comment by t0ssox** [comment]
FM Radio works for me without any problems on speaker/headphones.

**Comment by prin2ce** [comment]
@t0ssox thanks for replying, can you please tell that you use the native FM radio app or any 3rd party radio app because I have problems with native one

**Comment by prin2ce** [comment]
It started Working now out of nowhere +_+
