### ISSUE TITLE
Reboot to system doesn't work

### ISSUE THREAD

**Issue by prin2ce** [nichcream/rel#9]
Reboot to system doesn't work , reboot to recovery and bootloader works fine, same problem is their with other pie ROMs for santoni , was working good in oreo.

**Comment by nichcream** [comment]
"doesn't work" isn't enough to describe the issue.

**Comment by prin2ce** [comment]
In the first boot, FM radio no audio output was coming and when clicked on reboot to system it just showed rebooting to system and not doing anything, but when I rebooted the device everything is working fine now including FM radio   and rebooting to system also works
